# Generated by Django 5.1.4 on 2025-05-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePageApp', '0005_remove_blog_category_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(null=True, to='homePageApp.category'),
        ),
    ]
