# Generated by Django 5.1.4 on 2025-07-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePageApp', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
