# Generated by Django 5.1.4 on 2025-07-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePageApp', '0009_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
